Add Shellcheck

diff --git a/AppRun b/AppRun
--- a/AppRun
+++ b/AppRun
@@ -1,29 +1,26 @@
-#!/bin/bash
+#!/usr/bin/env bash
 set -e
 
-if [ ! -z "$DEBUG" ] ; then
-  env
-  set -x
+if [ -n "$DEBUG" ]; then
+	env
+	set -x
 fi
 
 THIS="$0"
-# http://stackoverflow.com/questions/3190818/
-args=("$@")
-NUMBER_OF_ARGS="$#"
 
-if [ -z "$APPDIR" ] ; then
-  # Find the AppDir. It is the directory that contains AppRun.
-  # This assumes that this script resides inside the AppDir or a subdirectory.
-  # If this script is run inside an AppImage, then the AppImage runtime likely has already set $APPDIR
-  path="$(dirname "$(readlink -f "${THIS}")")"
-  while [[ "$path" != "" && ! -e "$path/$1" ]]; do
-    path=${path%/*}
-  done
-  export APPDIR="$path"
+if [ -z "$APPDIR" ]; then
+	# Find the AppDir. It is the directory that contains AppRun.
+	# This assumes that this script resides inside the AppDir or a subdirectory.
+	# If this script is run inside an AppImage, then the AppImage runtime likely has already set $APPDIR
+	path="$(dirname "$(readlink -f "${THIS}")")"
+	while [[ "$path" != "" && ! -e "$path/$1" ]]; do
+		path=${path%/*}
+	done
+	export APPDIR="$path"
 fi
 path="$(dirname "$(readlink -f "${THIS}")")"
 export APPDIR="$path"
-echo $APPDIR
+echo "$APPDIR"
 
 export PATH="${APPDIR}:${APPDIR}/usr/sbin:${PATH}"
 export XDG_DATA_DIRS="./share/:/usr/share/gnome:/usr/local/share/:/usr/share/:${XDG_DATA_DIRS}"
@@ -33,60 +30,55 @@ export GSETTINGS_SCHEMA_DIR="${APPDIR}/usr/share/glib-2.0/schemas:${GSETTINGS_SC
 
 BIN="$APPDIR/pocketcasts-electron"
 
-if [ -z "$APPIMAGE_EXIT_AFTER_INSTALL" ] ; then
-  trap atexit EXIT
+if [ -z "$APPIMAGE_EXIT_AFTER_INSTALL" ]; then
+	trap atexit EXIT
 fi
 
-atexit()
-{
-  if [ $XDG_SESSION_TYPE == "wayland" ]
-  then
-    exec "$BIN" "--enable-features=UseOzonePlatform" "--ozone-platform=wayland"
-  else
-    exec "$BIN"
-  fi
+atexit() {
+	if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
+		exec "$BIN" "--enable-features=UseOzonePlatform" "--ozone-platform=wayland"
+	else
+		exec "$BIN"
+	fi
 }
 
-error()
-{
-  if [ -x /usr/bin/zenity ] ; then
-    LD_LIBRARY_PATH="" zenity --error --text "${1}" 2>/dev/null
-  elif [ -x /usr/bin/kdialog ] ; then
-    LD_LIBRARY_PATH="" kdialog --msgbox "${1}" 2>/dev/null
-  elif [ -x /usr/bin/Xdialog ] ; then
-    LD_LIBRARY_PATH="" Xdialog --msgbox "${1}" 2>/dev/null
-  else
-    echo "${1}"
-  fi
-  exit 1
+error() {
+	if [ -x /usr/bin/zenity ]; then
+		LD_LIBRARY_PATH="" zenity --error --text "${1}" 2>/dev/null
+	elif [ -x /usr/bin/kdialog ]; then
+		LD_LIBRARY_PATH="" kdialog --msgbox "${1}" 2>/dev/null
+	elif [ -x /usr/bin/Xdialog ]; then
+		LD_LIBRARY_PATH="" Xdialog --msgbox "${1}" 2>/dev/null
+	else
+		echo "${1}"
+	fi
+	exit 1
 }
 
-yesno()
-{
-  TITLE=$1
-  TEXT=$2
-  if [ -x /usr/bin/zenity ] ; then
-    LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" 2>/dev/null || exit 0
-  elif [ -x /usr/bin/kdialog ] ; then
-    LD_LIBRARY_PATH="" kdialog --title "$TITLE" --yesno "$TEXT" || exit 0
-  elif [ -x /usr/bin/Xdialog ] ; then
-    LD_LIBRARY_PATH="" Xdialog --title "$TITLE" --clear --yesno "$TEXT" 10 80 || exit 0
-  else
-    echo "zenity, kdialog, Xdialog missing. Skipping ${THIS}."
-    exit 0
-  fi
+yesno() {
+	TITLE=$1
+	TEXT=$2
+	if [ -x /usr/bin/zenity ]; then
+		LD_LIBRARY_PATH="" zenity --question --title="$TITLE" --text="$TEXT" 2>/dev/null || exit 0
+	elif [ -x /usr/bin/kdialog ]; then
+		LD_LIBRARY_PATH="" kdialog --title "$TITLE" --yesno "$TEXT" || exit 0
+	elif [ -x /usr/bin/Xdialog ]; then
+		LD_LIBRARY_PATH="" Xdialog --title "$TITLE" --clear --yesno "$TEXT" 10 80 || exit 0
+	else
+		echo "zenity, kdialog, Xdialog missing. Skipping ${THIS}."
+		exit 0
+	fi
 }
 
-check_dep()
-{
-  DEP=$1
-  if [ -z $(which "$DEP") ] ; then
-    echo "$DEP is missing. Skipping ${THIS}."
-    exit 0
-  fi
+check_dep() {
+	DEP=$1
+	if [ -z "$(which "$DEP")" ]; then
+		echo "$DEP is missing. Skipping ${THIS}."
+		exit 0
+	fi
 }
 
-if [ -z "$APPIMAGE" ] ; then
-  APPIMAGE="$APPDIR/AppRun"
-  # not running from within an AppImage; hence using the AppRun for Exec=
+if [ -z "$APPIMAGE" ]; then
+	APPIMAGE="$APPDIR/AppRun"
+	# not running from within an AppImage; hence using the AppRun for Exec=
 fi
